steps:
  # 1. Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'
      - '.'

  # 2. Pousser l'image dans Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'

  # 3. Déployer l'image sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mooc-web'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
