steps:
  # 1. Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'
      - '.'

  # 2. Pousser l'image dans Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'

  # 3. Se connecter au cluster GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'mooc-gke-cluster'
      - '--region'
      - 'us-west1'
      - '--project'
      - '$PROJECT_ID'

  # 4. Mettre à jour l'image du Deployment GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/monsiteweb'
      - 'mooc-web-sha256-1=europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'

  # 5. Vérifier le rollout Kubernetes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/monsiteweb'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mooc-containers/mooc-web:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
